apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - status-page.yaml
  - rbac.yaml
  - network-policy.yaml
  - ingress.yaml
  - image-automation.yaml
configMapGenerator:
  - name: status-page-catalog
    namespace: status-page
    files:
      - monitors.json
