apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: easy-swu-api
  namespace: flux-system
spec:
  image: ccr.ccs.tencentyun.com/lazycampus/easy-swu-api
  interval: 1h
  timeout: 1m0s
  secretRef:
    name: tcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: easy-swu-api
  namespace: flux-system
spec:
  filterTags:
    extract: $build
    pattern: ^1\.0\.(?P<build>[0-9]+)$
  imageRepositoryRef:
    name: easy-swu-api
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: easy-swu-admin
  namespace: flux-system
spec:
  image: ccr.ccs.tencentyun.com/lazycampus/easy-swu-admin
  interval: 1h
  timeout: 1m0s
  secretRef:
    name: tcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: easy-swu-admin
  namespace: flux-system
spec:
  filterTags:
    extract: $build
    pattern: ^1\.0\.(?P<build>[0-9]+)$
  imageRepositoryRef:
    name: easy-swu-admin
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: easy-swu
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@lazycampus.com
        name: Flux Image Automation
      messageTemplate: "chore(images): update easy-swu"
    push:
      branch: main
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/easy-platform/apps/easy-swu
    strategy: Setters
