apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - redis.yaml
  - minio.yaml
  - api.yaml
  - admin.yaml
  - ingress.yaml
  - backup.yaml
  - retention.yaml
  - network-policy.yaml
  - image-automation.yaml
