apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/gotk-sync.yaml
  - infrastructure/ingress
  - infrastructure/mysql
  - infrastructure/identity
  - infrastructure/domain-automation
  - apps/lazycampus-site
  - apps/bbbto-mnp
  - apps/smart-shop
