apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mysql-system
resources:
  - job.yaml
configMapGenerator:
  - name: mysql-memory-preflight
    files:
      - platform.cnf
      - verify.sh
