apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-reconciler-config
  namespace: domain-system
data:
  zones.json: |
    {
      "zones": [
        {
          "domain": "lazycampus.com",
          "mode": "edgeone",
          "cloudflareZoneId": "b3587d327b62aaef899b5936e4d6d272",
          "edgeoneZoneId": "zone-3solmvkeru39",
          "origin": "1.14.95.189",
          "originProtocol": "HTTP",
          "httpOriginPort": 80,
          "ipv6Status": "follow",
          "certificateMode": "eofreecert",
          "hostHeaderOverrides": {
            "lazycampus.com": "www.lazycampus.com"
          },
          "ttl": 1
        }
      ]
    }
