apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: educoder-wecom
  namespace: wecom-kf
  annotations:
    platform.lazycampus.com/domain-automation: enabled
spec:
  ingressClassName: traefik
  rules:
    - host: kf.lazycampus.com
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: educoder-wecom
                port:
                  name: http
          - path: /callbacks/wecom/kf
            pathType: Exact
            backend:
              service:
                name: educoder-wecom
                port:
                  name: http
          - path: /callbacks/payments
            pathType: Exact
            backend:
              service:
                name: educoder-wecom
                port:
                  name: http
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: educoder-wecom
                port:
                  name: http
          - path: /readyz
            pathType: Exact
            backend:
              service:
                name: educoder-wecom
                port:
                  name: http
