apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: platform-smoke
  namespace: flux-system
spec:
  image: ccr.ccs.tencentyun.com/lazycampus/platform-smoke
  interval: 1m0s
  secretRef:
    name: tcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: platform-smoke
  namespace: flux-system
spec:
  filterTags:
    extract: $build
    pattern: ^0\.1\.(?P<build>[0-9]+)$
  imageRepositoryRef:
    name: platform-smoke
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: platform-smoke
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@lazycampus.com
        name: Flux Image Automation
      messageTemplate: "chore(images): update automated images"
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/easy-platform/apps/platform-smoke
    strategy: Setters
