#!/usr/bin/env python3
"""Restore only the Status database from a local backup into a temporary schema."""
from pathlib import Path
import re
import secrets
import subprocess


def extract(lines, target):
    if not re.fullmatch(r"status_restore_[0-9a-f]{16}", target):
        raise ValueError("Invalid isolated restore database")
    active = False
    chunks = []
    size = 0
    for line in lines:
        if line.startswith("-- Current Database:"):
            if active:
                break
            active = line.strip() == "-- Current Database: `lazycampus_status`"
            continue
        if not active:
            continue
        if line.startswith("CREATE DATABASE"):
            continue
        # Full-dump epilogues may restore global server settings. They have no
        # place in an isolated database verification and must never be executed.
        if re.match(r"\s*(?:/\*![0-9]+\s*)?SET\s+(?:@@)?GLOBAL\b", line, re.I):
            continue
        if re.match(r"\s*(?:/\*![0-9]+\s*)?(?:DROP\s+DATABASE|ALTER\s+(?:DATABASE|USER|INSTANCE)|CREATE\s+USER|DROP\s+USER|GRANT|REVOKE|SHUTDOWN|RESET|PURGE|CHANGE)\b", line, re.I):
            raise ValueError("Server-level statement is not allowed in isolated restore")
        if line.strip() == "USE `lazycampus_status`;":
            line = f"USE `{target}`;\n"
        if re.match(r"\s*USE\s", line, re.I) and line.strip() != f"USE `{target}`;":
            raise ValueError("Unexpected database selection in backup")
        if re.match(r"\s*(?:/\*![0-9]+\s*)?(?:CREATE|ALTER).*\b(?:TRIGGER|EVENT|PROCEDURE|FUNCTION)\b", line, re.I):
            raise ValueError("Executable database objects require separate review")
        if "`lazycampus_status`." in line:
            raise ValueError("Cross-database reference in backup")
        size += len(line)
        if size > 64 * 1024 * 1024:
            raise ValueError("Status backup exceeds bounded restore size")
        chunks.append(line)
    if not active or not any("CREATE TABLE `components`" in line for line in chunks):
        raise ValueError("Backup does not contain Status tables")
    # An extracted final database can include mysqldump's global epilogue.
    # Initialize the session variables normally provided by the full dump header.
    header = """SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS;
SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION;
SET NAMES utf8mb4;
SET @OLD_TIME_ZONE=@@TIME_ZONE;
SET TIME_ZONE='+00:00';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0;
"""
    return header + "".join(chunks)


def sql(statement):
    result = subprocess.run(["k3s", "kubectl", "-n", "mysql-system", "exec", "-i", "mysql-0", "-c", "mysql", "--", "/bin/bash", "-ec", 'MYSQL_PWD="$MYSQL_ROOT_PASSWORD" exec mysql -uroot --batch --skip-column-names'], input=statement, capture_output=True, text=True, timeout=120)
    if result.returncode:
        match = re.search(r"ERROR (\d+).*?at line (\d+)", result.stderr)
        detail = f" (MySQL {match[1]}, statement line {match[2]})" if match else ""
        raise RuntimeError("Isolated restore verification failed" + detail + "; no database content displayed")
    return result.stdout.strip()


def main():
    backups = sorted(Path("/srv/k3s-backups/mysql").glob("all-databases-*.sql"), key=lambda p: p.stat().st_mtime)
    if not backups:
        raise SystemExit("No completed local database backup found")
    # Clean up only schemas generated by interrupted runs of this exact check.
    for leftover in sql("SELECT SCHEMA_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME REGEXP '^status_restore_[0-9a-f]{16}$';").splitlines():
        if re.fullmatch(r"status_restore_[0-9a-f]{16}", leftover):
            sql(f"DROP DATABASE `{leftover}`;")
    source = backups[-1]
    target = "status_restore_" + secrets.token_hex(8)
    with source.open(encoding="utf8") as stream:
        payload = extract(stream, target)
    created = False
    try:
        sql(f"CREATE DATABASE `{target}` CHARACTER SET utf8mb4;")
        created = True
        sql(f"USE `{target}`;\n" + payload)
        for table in ("components", "incidents", "subscriptions", "audit"):
            count = sql(f"SELECT COUNT(*) FROM `{target}`.`{table}`;")
            if not count.isdigit():
                raise RuntimeError("Invalid verification result")
            print(f"Restored {table}: {count} rows readable")
        print(f"Verified local backup: {source.name}")
    finally:
        if created and re.fullmatch(r"status_restore_[0-9a-f]{16}", target):
            sql(f"DROP DATABASE `{target}`;")
            print("Temporary verification database removed; production database unchanged.")


if __name__ == "__main__":
    main()
