apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bbbto-mnp
  namespace: flux-system
spec:
  image: ccr.ccs.tencentyun.com/lazycampus/bbbto-mnp
  interval: 1h
  timeout: 1m0s
  secretRef:
    name: tcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bbbto-mnp
  namespace: flux-system
spec:
  filterTags:
    extract: $build
    pattern: ^1\.0\.(?P<build>[0-9]+)$
  imageRepositoryRef:
    name: bbbto-mnp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: bbbto-mnp
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@lazycampus.com
        name: Flux Image Automation
      messageTemplate: "chore(images): update bbbto-mnp"
    push:
      branch: main
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/easy-platform/apps/bbbto-mnp
    strategy: Setters
