apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: identity-bridge
  namespace: flux-system
spec:
  image: ccr.ccs.tencentyun.com/lazycampus/identity-bridge
  interval: 1h
  timeout: 1m0s
  secretRef:
    name: tcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: identity-bridge
  namespace: flux-system
  labels:
    platform.lazycampus.com/image-automation: platform-images
spec:
  filterTags:
    extract: $build
    pattern: ^1\.0\.(?P<build>[0-9]+)$
  imageRepositoryRef:
    name: identity-bridge
  policy:
    numerical:
      order: asc
