apiVersion: v1
kind: Service
metadata:
  name: tailscale-proxy
  namespace: tailscale-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tailscale-proxy
  ports:
    - name: proxy
      port: 1055
      targetPort: proxy
      protocol: TCP
    - name: health
      port: 9002
      targetPort: health
      protocol: TCP
